### ISSUE TITLE
YSFlight source code is opensource now

### ISSUE THREAD

**Issue by ghost** [mido3ds/OpenYSF#1]
Original *YSFlight* source code now released:

- Source - https://github.com/captainys/YSFLIGHT
- Discussion - https://forum.ysfhq.com/viewtopic.php?f=167&t=10850

You might be interested to join its development ;-)

**Comment by mido3ds** [comment]
Thank you for letting me know!

I'm happy to hear that.

I will keep this project to experiment with ideas and learn, maybe a eewrite is easier to work with than the original.
